### ISSUE TITLE
number of clients is always 1000

### ISSUE THREAD

**Issue by HigginsDeveloper** [processone/rtb#13]
How do I create a topic in MQTT mode? Subscribe to topics? And how do I send a message to a topic? What command to execute

**Comment by licaon-kter** [comment]
So you've created 2000 users with `priv/bin/rtb_db -t mosquitto -c 2000 -u user% -p pass%` right?

**Comment by licaon-kter** [comment]
Why do you keep editing your messages? It's okay to be wrong...

Everything is automated, you just look at the pretty graphs.
