### ISSUE TITLE
No stream features to proceed with?

### ISSUE THREAD

**Issue by PolynomialDivision** [processone/rtb#15]
Actually, I wanted to use rtb to debug memory leakage in Jitsi. In particular, in the Jicofo component.
https://groups.google.com/forum/#!topic/prosody-users/qb3bynuJJVc

To get familar with rtb I installed on Manjaro/Arch/Debian my own prosody hosting, and tried to use rtb. But I always get the same error:

> [critical] Benchmark failure: Stream closed by peer: No stream features to proceed with (undefined-condition)

On prosody side:

> Should be able to do TLS but no context available
> No stream features to offer
> Disconnecting client, <stream:error> is: <stream:error><undefined-condition xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmln>
> Sending[c2s_unauthed]: <stream:error>
> Sending[c2s_unauthed]: </stream:stream>
> c2s stream for 127.0.0.1 closed: No stream features to proceed with
> Destroying session for (unknown) ((unknown)@localhost): No stream features to proceed with
> Client disconnected: connection closed
> Destroying session for (unknown) ((unknown)@(unknown))
> closed client handler and removed socket from list

Could u maybe give some hints what is wrong?

**Comment by licaon-kter** [comment]
You have `mod_smacks` loaded?

**Comment by licaon-kter** [comment]
@PolynomialDivision Regardin the MUC issue you are aware of https://github.com/jitsi/jicofo/issues/470 ? Can you update to HEAD and retry, ref: https://github.com/jitsi/jicofo/pull/494 ?

Did you switch to the new MUC connection between jicofo and the videobridge? https://github.com/jitsi/jitsi-videobridge/blob/master/doc/muc.md

For ejabberd the muc health check was problematic too: https://github.com/processone/ejabberd/issues/3236
