### ISSUE TITLE
Query about rtb rooms

### ISSUE THREAD

**Issue by amitchauhan1502** [processone/rtb#17]
Does rtb create rooms, distribute and assign users automatically based on number of users 
OR 
we need to create rooms manually and subscribe users explicitly to the created rooms.

In the first case how we can create small, medium and large rooms if rtb does it automatically. For example :
muc_rooms:
  - large1@conference.domain.tld
  - medium[1..10]@conference.domain.tld
  - small[1..100]@conference.domain.tld

**Comment by licaon-kter** [comment]
First case yes, rtb makes the rooms and populates them, see readme.

**Comment by amitchauhan1502** [comment]
Hi, Got your point. 
Just wanna understand how users will be assigned to small, medium and large rooms and in what number. Users can't be distributed uniformly across small, medium and large rooms. I mean whats the criteria for assigning how many users to a set of small, medium and large rooms if I declare my rooms like:
muc_rooms:
large1@conference.domain.tld
medium[1..10]@conference.domain.tld
small[1..100]@conference.domain.tld

**Comment by licaon-kter** [comment]
1 room? Total number of users
10 rooms? Total divided by 10 for each room
... 


Depends on usecase, maybe that large room isn't necessary, will you have a 20000 users room?

**Comment by amitchauhan1502** [comment]
OK. Thanks
For how much time rtb load test (for ejabberd) should run ? Is there a standard formula or criteria to decide based on some config parameters ?

**Comment by licaon-kter** [comment]
How much depends on your usecase, you want to test a loaded server... "for how much time" will your server be loaded with real users?

**Comment by amitchauhan1502** [comment]
Thanks for your response
