### ISSUE TITLE
Problems compiling rtb with Erlang/OTP 23

### ISSUE THREAD

**Issue by amitchauhan1502** [processone/rtb#18]
While doing rtb "make" I am facing following issue

/usr/bin/ld: cannot find -lerl_interface
collect2: error: ld returned 1 exit status

I tried to locate liberl_interface.a but its not traceable. Any help in this regard would be great

**Comment by licaon-kter** [comment]
`erlang-dev` or whatever is installed?

**Comment by amitchauhan1502** [comment]
yes, 
erlang-dev is already the newest version (1:23.0.2-1).

root@xmpp:~/rtb# erl
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1]

**Comment by licaon-kter** [comment]
23? Right... rename this issue to `Problems compiling rtb with Erlang/OTP 23` then

Ref: https://github.com/processone/ejabberd/issues/3282

Ping @badlop

**Comment by badlop** [comment]
I've adapted the solution applied in ejabberd. Now it compiles for me and should have no drawback.
